[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
rpc = {path = "../rpc"}
futures-util = "0.3"
futures-channel = "0.3"
include_dir = "0.7.4"
kiss3d = { version = "0.42.0", features = ["egui"]}
rkyv = {workspace = true}
bytes = {workspace = true}
console_error_panic_hook = "0.1.7"
futures = "0.3.32"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = {workspace = true}
tokio-tungstenite = {workspace = true}
tokio-stream = {workspace = true}
time = "0.3.47"


[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
ws_stream_wasm = "0.7.5"
gloo-timers = { version = "0.4.0", features = ["futures"] }
time = { version = "0.3.47", features = ["wasm-bindgen"] }

