[workspace]
resolver = "3"
members = ["client", "rpc", "server"]

[workspace.lints.clippy]
unwrap_used = "deny"
panic = "deny"

[workspace.dependencies]
rkyv = { version = "0.8.16", features = ["uuid-1"] }
bytes = "1.11.1"
tokio = {version = "1.52.3", features = ["full"] }
web-transport = "0.10.6"
tokio-stream = "0.1"
uuid = {version = "1.23.2", features = ["v4", "rng-getrandom"] }
glam = {version = "0.33", features = ["rkyv", "serde", "bytecheck"]}
rapier2d = { version = "0.33", features = ["serde-serialize", "bytemuck"] }
# we're using straight from git because of extra bug fixes and whatnot
hecs = {git = "https://github.com/Ralith/hecs.git", rev = "e57c6c895a1a1748746ffa4c6358ac448375e71c"}
url = { version = "2.5.8" }
