[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
rpc = {path = "../rpc"}
futures-util = "0.3.32"
tokio = {workspace = true}
web-transport-quinn = "0.11.9"
tokio-stream = {workspace = true}
rkyv = {workspace = true}
uuid = {workspace = true }
anyhow = "1.0.102"
rustls = "0.23.40"
clap = { version = "4", features = ["derive"] }
rustls-pemfile = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
rapier2d = {workspace = true}
hecs = {workspace = true}
dotenvy = "0.15.7"
oauth2 = "5.0.0"
url = {workspace = true}
axum = "0.8.9"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
